# Generated by Django 4.1.2 on 2022-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('marks', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
